---

# Based on https://github.com/andrewrothstein/ansible-anaconda/blob/master/tasks/default.yml
- name: Download Installer
  get_url:
    url: '{{anaconda_installer_url}}'
    dest: /tmp/{{anaconda_installer_sh}}
    timeout: '{{anaconda_timeout_seconds}}'
    checksum: '{{anaconda_checksum}}'
    mode: 0755

- name: Install Anaconda
  command: /tmp/{{anaconda_installer_sh}} -b -p {{anaconda_install_dir}}
  args:
    creates: '{{anaconda_install_dir}}'

- name: Delete Installer...
  file:
    path: /tmp/{{anaconda_installer_sh}}
    state: absent

- name: Link Anaconda
  file:
    src: '{{anaconda_install_dir}}'
    dest: '{{anaconda_link_dir}}'
    state: link

- name: Update Anaconda Packages
  when: anaconda_pkg_update
  command: '{{anaconda_link_dir}}/bin/conda update -y --all'
